#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "11i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
service nginx restart

