#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
service nginx restart
