#!/usr/bin/env bash
#generates a MySQL dump and creates a compressed archive out of it.

sudo mysqldump -u root -p'$1' --opt --all-databases> backup.sql;
sudo tar-zcvf"$(date +'%m-%d-%y)".tar.gz backup.sql;
