#!/usr/bin/env bash
#a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations

d=1

while [ "$d" -le "10" ]
do
	if [ "$d" == "4" ]
		then
		echo "bad luck"
	elif [ "$d" == "8" ]
		then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((d++))
done
