#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

content="$(ls)"

for d in $content
do
	echo "$d" | cut -d '-' -f 2
done
