#!/usr/bin/env bash
# Nginx is running as the nginx user

pkill apache2
sudo chmod 744 /etc/nginx/nginx.conf
sed -i '2i user nginx;' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx -c 'service nginx start'
