#!/usr/bin/env bash
# Running Nginx as nginx user and listening on all active IPS on port 8080

sudo pkill apache2
sudo chmod 600 /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
